I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 52, in script
    with fadeout
  File "game/script.rpy", line 52, in <module>
    with fadeout
NameError: name 'fadeout' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 52, in script
    with fadeout
  File "D:\source\renpy-sdk\renpy-8.3.4-sdk\renpy\ast.py", line 1360, in execute
    trans = renpy.python.py_eval(self.expr)
  File "D:\source\renpy-sdk\renpy-8.3.4-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\source\renpy-sdk\renpy-8.3.4-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 52, in <module>
    with fadeout
NameError: name 'fadeout' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.3.4.24120703
TouHouESUgirls 1.0
Fri Jan 17 23:21:32 2025
